// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/turkprogrammer/taskflow/internal/service (interfaces: ReportStore)

package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	store "github.com/turkprogrammer/taskflow/internal/store"
)

// MockReportStore is a mock of ReportStore interface.
type MockReportStore struct {
	ctrl     *gomock.Controller
	recorder *MockReportStoreMockRecorder
}

// MockReportStoreMockRecorder is the mock recorder for MockReportStore.
type MockReportStoreMockRecorder struct {
	mock *MockReportStore
}

// NewMockReportStore creates a new mock instance.
func NewMockReportStore(ctrl *gomock.Controller) *MockReportStore {
	mock := &MockReportStore{ctrl: ctrl}
	mock.recorder = &MockReportStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportStore) EXPECT() *MockReportStoreMockRecorder {
	return m.recorder
}

// GetInefficientTasks mocks base method.
func (m *MockReportStore) GetInefficientTasks(arg0 context.Context) ([]store.InefficientTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInefficientTasks", arg0)
	ret0, _ := ret[0].([]store.InefficientTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInefficientTasks indicates an expected call of GetInefficientTasks.
func (mr *MockReportStoreMockRecorder) GetInefficientTasks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInefficientTasks", reflect.TypeOf((*MockReportStore)(nil).GetInefficientTasks), arg0)
}

// GetTeamDashboard mocks base method.
func (m *MockReportStore) GetTeamDashboard(arg0 context.Context, arg1 uint64) (*store.TeamDashboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamDashboard", arg0, arg1)
	ret0, _ := ret[0].(*store.TeamDashboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamDashboard indicates an expected call of GetTeamDashboard.
func (mr *MockReportStoreMockRecorder) GetTeamDashboard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamDashboard", reflect.TypeOf((*MockReportStore)(nil).GetTeamDashboard), arg0, arg1)
}

// GetTopUsersPerTeam mocks base method.
func (m *MockReportStore) GetTopUsersPerTeam(arg0 context.Context) ([]store.TopUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopUsersPerTeam", arg0)
	ret0, _ := ret[0].([]store.TopUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopUsersPerTeam indicates an expected call of GetTopUsersPerTeam.
func (mr *MockReportStoreMockRecorder) GetTopUsersPerTeam(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopUsersPerTeam", reflect.TypeOf((*MockReportStore)(nil).GetTopUsersPerTeam), arg0)
}
