// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/turkprogrammer/taskflow/internal/service (interfaces: TaskStore)
//
// Generated by this command:
//
//	mockgen -destination=internal\service\mocks\task_store.go -package=mocks github.com/turkprogrammer/taskflow/internal/service TaskStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	store "github.com/turkprogrammer/taskflow/internal/store"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskStore is a mock of TaskStore interface.
type MockTaskStore struct {
	ctrl     *gomock.Controller
	recorder *MockTaskStoreMockRecorder
	isgomock struct{}
}

// MockTaskStoreMockRecorder is the mock recorder for MockTaskStore.
type MockTaskStoreMockRecorder struct {
	mock *MockTaskStore
}

// NewMockTaskStore creates a new mock instance.
func NewMockTaskStore(ctrl *gomock.Controller) *MockTaskStore {
	mock := &MockTaskStore{ctrl: ctrl}
	mock.recorder = &MockTaskStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskStore) EXPECT() *MockTaskStoreMockRecorder {
	return m.recorder
}

// AppendHistory mocks base method.
func (m *MockTaskStore) AppendHistory(ctx context.Context, taskID, changedBy uint64, field, oldVal, newVal string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendHistory", ctx, taskID, changedBy, field, oldVal, newVal)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendHistory indicates an expected call of AppendHistory.
func (mr *MockTaskStoreMockRecorder) AppendHistory(ctx, taskID, changedBy, field, oldVal, newVal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendHistory", reflect.TypeOf((*MockTaskStore)(nil).AppendHistory), ctx, taskID, changedBy, field, oldVal, newVal)
}

// Create mocks base method.
func (m *MockTaskStore) Create(ctx context.Context, t *store.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTaskStoreMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskStore)(nil).Create), ctx, t)
}

// GetByID mocks base method.
func (m *MockTaskStore) GetByID(ctx context.Context, id uint64) (*store.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*store.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskStoreMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskStore)(nil).GetByID), ctx, id)
}

// GetHistory mocks base method.
func (m *MockTaskStore) GetHistory(ctx context.Context, taskID uint64) ([]*store.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, taskID)
	ret0, _ := ret[0].([]*store.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockTaskStoreMockRecorder) GetHistory(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockTaskStore)(nil).GetHistory), ctx, taskID)
}

// IsMember mocks base method.
func (m *MockTaskStore) IsMember(ctx context.Context, teamID, userID uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, teamID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockTaskStoreMockRecorder) IsMember(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockTaskStore)(nil).IsMember), ctx, teamID, userID)
}

// List mocks base method.
func (m *MockTaskStore) List(ctx context.Context, filter store.TaskFilter) ([]*store.Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*store.Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskStoreMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskStore)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockTaskStore) Update(ctx context.Context, t *store.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaskStoreMockRecorder) Update(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskStore)(nil).Update), ctx, t)
}
