// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/turkprogrammer/taskflow/internal/service (interfaces: TeamStore)
//
// Generated by this command:
//
//	mockgen -destination=internal\service\mocks\team_store.go -package=mocks github.com/turkprogrammer/taskflow/internal/service TeamStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	store "github.com/turkprogrammer/taskflow/internal/store"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamStore is a mock of TeamStore interface.
type MockTeamStore struct {
	ctrl     *gomock.Controller
	recorder *MockTeamStoreMockRecorder
	isgomock struct{}
}

// MockTeamStoreMockRecorder is the mock recorder for MockTeamStore.
type MockTeamStoreMockRecorder struct {
	mock *MockTeamStore
}

// NewMockTeamStore creates a new mock instance.
func NewMockTeamStore(ctrl *gomock.Controller) *MockTeamStore {
	mock := &MockTeamStore{ctrl: ctrl}
	mock.recorder = &MockTeamStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamStore) EXPECT() *MockTeamStoreMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockTeamStore) AddMember(ctx context.Context, teamID, userID uint64, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, teamID, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockTeamStoreMockRecorder) AddMember(ctx, teamID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockTeamStore)(nil).AddMember), ctx, teamID, userID, role)
}

// Create mocks base method.
func (m *MockTeamStore) Create(ctx context.Context, t *store.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTeamStoreMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamStore)(nil).Create), ctx, t)
}

// CreateWithOwner mocks base method.
func (m *MockTeamStore) CreateWithOwner(ctx context.Context, t *store.Team, ownerID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithOwner", ctx, t, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithOwner indicates an expected call of CreateWithOwner.
func (mr *MockTeamStoreMockRecorder) CreateWithOwner(ctx, t, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithOwner", reflect.TypeOf((*MockTeamStore)(nil).CreateWithOwner), ctx, t, ownerID)
}

// GetByID mocks base method.
func (m *MockTeamStore) GetByID(ctx context.Context, id uint64) (*store.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*store.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTeamStoreMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTeamStore)(nil).GetByID), ctx, id)
}

// GetMemberRole mocks base method.
func (m *MockTeamStore) GetMemberRole(ctx context.Context, teamID, userID uint64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberRole", ctx, teamID, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberRole indicates an expected call of GetMemberRole.
func (mr *MockTeamStoreMockRecorder) GetMemberRole(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberRole", reflect.TypeOf((*MockTeamStore)(nil).GetMemberRole), ctx, teamID, userID)
}

// GetMembers mocks base method.
func (m *MockTeamStore) GetMembers(ctx context.Context, teamID uint64) ([]*store.TeamMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers", ctx, teamID)
	ret0, _ := ret[0].([]*store.TeamMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers.
func (mr *MockTeamStoreMockRecorder) GetMembers(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockTeamStore)(nil).GetMembers), ctx, teamID)
}

// ListByUserID mocks base method.
func (m *MockTeamStore) ListByUserID(ctx context.Context, userID uint64) ([]*store.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]*store.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockTeamStoreMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockTeamStore)(nil).ListByUserID), ctx, userID)
}
